# terraform - github workflow
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: terraform

on:
  push:

  # enable manual workflow
  workflow_dispatch:
    inputs: {}

# permissions for oidc login
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  PREFIX: arshz
  LOCATION: eastus

  # debug
  CI_DEBUG: true

  # azure auth from secrets
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}

  # terraform
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_PLAN: "tfplan"
  # https://github.com/hashicorp/terraform/releases
  TF_VERSION: "1.3.3"

  # Env var concatenation is currently not supported at Workflow or Job scope. See workaround below:
  # https://github.community/t5/GitHub-Actions/How-can-we-concatenate-multiple-env-vars-at-workflow-and-job/td-p/48489

jobs:
  terraform:
    # always pin versions
    # view installed software: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-software
    runs-on: ubuntu-22.04

    # only run if owner triggered action
    if: github.actor == github.event.repository.owner.login

    steps:
      # Checkout
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # Init tasks - inc Env var concatenation
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
      - name: Init tasks - inc Env var concatenation (Workaround)
        run: |
          chmod -R +x ./scripts/
          echo "TERRAFORM_STORAGE_ACCOUNT=${{ env.PREFIX }}sttfstate${{ env.LOCATION }}" >> $GITHUB_ENV
          echo "TERRAFORM_STORAGE_RG=${{ env.PREFIX }}-rg-tfstate" >> $GITHUB_ENV

      # Login
      # https://github.com/Azure/login
      - name: Login via OIDC to Azure Public Cloud (az cli and az powershell)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # - name: Create Terraform Backend Storage
      #   run: ./scripts/terraform_backend_storage.sh

      # Terraform
      # https://github.com/hashicorp/setup-terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init / Validate / Apply
        # run: ./scripts/terraform_apply.sh
        run: |
          terraform init \
            -backend-config="resource_group_name=$TERRAFORM_STORAGE_RG" \
            -backend-config="storage_account_name=$TERRAFORM_STORAGE_ACCOUNT"

          # validate
          terraform validate

          # apply
          terraform apply -auto-approve
